name: MakePDFs

on: workflow_dispatch

jobs:
 makepdfs:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         repository: OWASP/CheatSheetSeries
     - uses: mkrakowitzer/actions-makepdfs@master
       with:
         markdown_dir: cheatsheets
         output_dir: tmp
     - uses: actions/upload-artifact@v4
       with:
         name: cheatsheets
         path: tmp
     
         

