name: MakePDFs

on: workflow_dispatch

jobs:
 makepdfs:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         repository: OWASP/CheatSheetSeries
     - uses: baileyjm02/markdown-to-pdf@v1
       with:
         input_path: cheatsheets
         images_dir: assets
         image_import: ../assets
         output_dir: tmp
         build_html: false
     - uses: actions/upload-artifact@v4
       with:
         name: cheatsheets
         path: tmp
     
         

